# See https://pre-commit.com for usage and config tips.
# Run `pre-commit install` after cloning to enable the hooks locally.

ci:
  autofix_prs: false
  skip: []

exclude: |
  (?x)(
    ^\.venv/ |
    ^node_modules/ |
    ^\.next/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        files: ^(backend|services|scripts)/.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(backend|services|scripts)/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^(backend|services|scripts)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.2.5"]
        files: ^frontend/
